driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://database-demo.cqqqbp9lubnd.ap-northeast-2.rds.amazonaws.com:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
username: admin
password: qufdk12ekfdk12^^